spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogs?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: czw123
    driver-class-name: com.mysql.cj.jdbc.Driver
#  resources:
#    static-locations:


#    文件上传设置
#  http:
#    multipart:
#      max-file-size: 15Mb
#      max-request-size: 60Mb

#mybatis:
##  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:com.czw.music.dao.*.xml
#  type-aliases-package: com.czw.entit

